version: '3.8'

services:
  postgres:
    image: postgres:15-alpine3.21
    container_name: tennisclub_db
    environment:
      POSTGRES_USER: tennis
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tennisclub
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: tennisclub_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE__PASSWORD: admin
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/tennisclub
    depends_on:
      - postgres

volumes:
  postgres-data:
